name: Daily news nacional Reporter

on:
  schedule:
    - cron: '0 10 * * *'  # 07:00 AM Argentina
  workflow_dispatch:

jobs:
  run_reporter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python news_nacional_reporter.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          WORDPRESS_USER: ${{ secrets.WORDPRESS_USER }}
          WORDPRESS_APP_PASSWORD: ${{ secrets.WORDPRESS_APP_PASSWORD }}
          WORDPRESS_URL: ${{ secrets.WORDPRESS_URL }}
